### ISSUE TITLE
Failed to connect to SQL 

### ISSUE THREAD

**Issue by jatinvmehta** [awslabs/aws-serverless-express#121]
1419:7)
    at Connection.tedious.once.err (/var/task/node_modules/mssql/lib/tedious.js:216:17)
    at Connection.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Connection.connectTimeout (/var/task/node_modules/tedious/lib/connection.js:634:12)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
  code: 'ETIMEOUT',
  originalError: 
   { ConnectionError: Failed to connect to 172.31.121.231:1433 in 15000ms
       at ConnectionError (/var/task/node_modules/tedious/lib/errors.js:12:12)
       at Connection.connectTimeout (/var/task/node_modules/tedious/lib/connection.js:634:28)
       at ontimeout (timers.js:386:14)
       at tryOnTimeout (timers.js:250:5)
       at Timer.listOnTimeout (timers.js:214:5)
     message: 'Failed to connect to 172.31.121.231:1433 in 15000ms',
     code: 'ETIMEOUT' },
  name: 'ConnectionError' }
2018-02-12T20:30:17.316Z	899267fc-1033-11e8-8515-ffe782c56967	Event: {"body":"{}","resource":"/{proxy+}","requestContext":{"resourceId":"123456","apiId":"1234567890","resourcePath":"/{proxy+}","httpMethod":"GET","requestId":"c6af9ac6-7b61-11e6-9a41-93e8deadbeef","accountId":"123456789012","identity":{"apiKey":null,"userArn":null,"cognitoAuthenticationType":null,"caller":null,"userAgent":"Custom User Agent String","user":null,"cognitoIdentityPoolId":null,"cognitoIdentityId":null,"cognitoAuthenticationProvider":null,"sourceIp":"127.0.0.1","accountId":null},"stage":"prod"},"queryStringParameters":{"maskurl":"~/wom/pregnancy/to-the-pregnant-mom-who-is-feeling-anything-but-sexy"},"headers":{"Via":"1.1 08f323deadbeefa7af34d5feb414ce27.cloudfront.net (CloudFront)","Accept-Language":"en-US,en;q=0.8","CloudFront-Is-Desktop-Viewer":"true","CloudFront-Is-SmartTV-Viewer":"false","CloudFront-Is-Mobile-Viewer":"false","X-Forwarded-For":"127.0.0.1, 127.0.0.2","CloudFront-Viewer-Country":"US","Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","Upgrade-Insecure-Requests":"1","X-Forwarded-Port":"443","Host":"1234567890.execute-api.us-east-1.amazonaws.com","X-Forwarded-Proto":"https","X-Amz-Cf-Id":"cDehVQoZnx43VYQb9j2-nvCh-9z396Uhbp027Y2JvkCPNLmGJHqlaA==","CloudFront-Is-Tablet-Viewer":"false","Cache-Control":"max-age=0","User-Agent":"Custom User Agent String","CloudFront-Forwarded-Proto":"https","Accept-Encoding":"gzip, deflate, sdch"},"pathParameters":{"proxy":"path/to/resource"},"httpMethod":"GET","stageVariables":{"baz":"qux"},"path":"/api/page"}
2018-02-12T20:30:17.376Z	899267fc-1033-11e8-8515-ffe782c56967	{ ConnectionError: Connection is closed.
    at ConnectionError (/var/task/node_modules/mssql/lib/base.js:1424:7)
    at Request._execute (/var/task/node_modules/mssql/lib/base.js:1378:37)
    at Request._execute (/var/task/node_modules/mssql/lib/tedious.js:803:11)
    at Request.execute (/var/task/node_modules/mssql/lib/base.js:1317:12)
    at /var/task/server.js:128:17
    at _poolCreate.then.catch.err (/var/task/node_modules/mssql/lib/base.js:270:7) code: 'ECONNCLOSED', name: 'ConnectionError' }
2018-02-12T20:30:17.436Z	899267fc-1033-11e8-8515-ffe782c56967	This is changed
2018-02-12T20:30:17.436Z	899267fc-1033-11e8-8515-ffe782c56967	~/testurl
2018-02-12T20:30:17.494Z	899267fc-1033-11e8-8515-ffe782c56967	ERROR: aws-serverless-express connection error
2018-02-12T20:30:17.494Z	899267fc-1033-11e8-8515-ffe782c56967	{ Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketOnEnd (_http_client.js:345:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9) code: 'ECONNRESET' }
END RequestId: 899267fc-1033-11e8-8515-ffe782c56967
REPORT RequestId: 899267fc-1033-11e8-8515-ffe782c56967	Duration: 222.42 ms	Billed Duration: 300 ms 	Memory Size: 128 MB	Max Memory Used: 37 MB

**Comment by AndybSe** [comment]
Hi
Check that the SQL server at 172.31.121.231 port 1433 is accessible ( online and firewall is open ). 
Best regards
Andreas
