### ISSUE TITLE
"Typerror: path contains unescaped characters" when ran locally

### ISSUE THREAD

**Issue by OmniPotent42** [awslabs/aws-serverless-express#132]
I recently got my API up and running locally with [SAM Local](https://github.com/awslabs/aws-sam-local) and I get this error when I try to use URL encoding. In my case the endpoint I am hitting looks like this: `localhost:3000/albums/Test%20Album`

When I deploy to API Gateway and test there it works fine, so I am not sure if it is a problem with this package or SAM Local. Here is the whole error stack that shows up in my console:

```
START RequestId: 9705d5d5-5b1d-1958-861e-e11556956cdd Version: $LATEST
2018-03-10T06:50:46.733Z        9705d5d5-5b1d-1958-861e-e11556956cdd    ERROR: aws-serverless-express error
2018-03-10T06:50:46.733Z        9705d5d5-5b1d-1958-861e-e11556956cdd    TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:52:11)
    at Object.exports.request (http.js:31:10)
    at forwardRequestToNodeServer (/var/task/node_modules/aws-serverless-express/index.js:118:26)
    at proxy (/var/task/node_modules/aws-serverless-express/index.js:182:7)
    at Server.startServer.on (/var/task/node_modules/aws-serverless-express/index.js:186:32)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1284:10)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
END RequestId: 9705d5d5-5b1d-1958-861e-e11556956cdd
REPORT RequestId: 9705d5d5-5b1d-1958-861e-e11556956cdd  Duration: 311.17 ms     Billed Duration: 400 ms Memory Size: 128 MB     Max Memory Used: 51 MB
```

**Comment by brettstack** [comment]
What SAM Local command are you running? If you're using an event, check the `path` property and ensure it doesn't have a space as described here https://stackoverflow.com/questions/31024779/typeerror-request-path-contains-unescaped-characters-how-can-i-fix-this/31588964

**Comment by OmniPotent42** [comment]
I am running `sam local start-api` and trying to access a route located at '/albums/:name' where `name` is a url encoded value. I have since changed it to use a query parameter instead which works.

**Comment by brettstack** [comment]
Closing this as it sounds like a SAM Local issue.
