### ISSUE TITLE
require npm 

### ISSUE THREAD

**Issue by dfloresgonz** [awslabs/aws-serverless-express#135]
I need to require pg-promise how can I achieve it?

**Comment by brettstack** [comment]
`npm install pg-promise` should be all you need.

**Comment by dfloresgonz** [comment]
should I do it in my local env and the push to codemmit? and wait for it to deploy?

**Comment by brettstack** [comment]
I'm not sure what your setup looks like. Do you have a CD pipeline set up to deploy your Lambda? Are you checking in your node_modules directory to source or is it running `npm install` in your pipeline? It should be exact same as how you installed Express and aws-serverless-express

**Comment by dfloresgonz** [comment]
I use codeStar, nodeJS in my local env, I just push my code to codecommit and autodeploys, I did npm install pg-promise and pushed it I got a different error now.

**Comment by dfloresgonz** [comment]
I get this error
`TypeError: Buffer.alloc is not a function
    at Object.<anonymous> (/var/task/node_modules/pg/lib/connection.js:290:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/task/node_modules/pg/lib/client.js:19:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)`

Googling I found this Node 4.5.0+ is required for Buffer.alloc. The new Buffer API is only available in v5.10.0+, so you'll need to upgrade to use it.

**Comment by dfloresgonz** [comment]
current version is v4.3.2 how can i upgrade?

**Comment by vitaly-t** [comment]
You should use the latest version of pg-promise :wink: (current is 8.2.2)

And the oldest Node.js needed for that is v4.5 :wink:
