### ISSUE TITLE
ERR_UNESCAPED_CHARACTERS

### ISSUE THREAD

**Issue by CarlosV89** [awslabs/aws-serverless-express#163]
Hey Guys, im trying to get this package working for a typescript project, so I have serverless with serverless-webpack plugin transpiling my code, all Is well until I actually try to hit the endpoint I created (which is a graphql enpoint wrapped in a NestJS Application), im getting the following error:
```
ERROR: aws-serverless-express error
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:127:13)
    at Object.request (http.js:38:10)
    at forwardRequestToNodeServer (/home/sidhenidon/Projects/clasify-serverless/node_modules/aws-serverless-express/index.js:119:26)
    at proxy (/home/sidhenidon/Projects/clasify-serverless/node_modules/aws-serverless-express/index.js:183:7)
    at Server.startServer.on (/home/sidhenidon/Projects/clasify-serverless/node_modules/aws-serverless-express/index.js:187:32)
    at Server.emit (events.js:132:15)
    at Server.emit (domain.js:439:23)
    at emitListeningNT (net.js:1388:10)
    at process._tickCallback (internal/process/next_tick.js:114:19)
Serverless: [200] {"statusCode":500,"body":"","headers":{}}
```

I included that line so you could see the response I got back from calling it

**Comment by brettstack** [comment]
What's the URL you're trying to hit? I've read whitespace is a common cause

**Comment by CarlosV89** [comment]
Just a regular `localhost:3000/graph` GET

**Comment by CarlosV89** [comment]
Hey @brettstack, I think I've found the reason why its giving me this error, in my serverless.yml; I was defining my function like this:
```
functions:
  graph:
    handler: src/graph/main.graph
    events:
      - http:
          method: get
          path: graph
          integration: lambda
```
`integration: lambda` is the offending line, I removed this and it seems to be working as expected

**Comment by brettstack** [comment]
Glad to hear you got it working. Closing this issue

**Comment by SeratoSD** [comment]
Hi @brettstack I'm facing the same issue but it's due to whitespace as you said.
Im trying to hit:   http://127.0.0.1:3000/api/v1/analyze-entities/ 1

¿ What can I do ?
