### ISSUE TITLE
can't run handler asynchronously

### ISSUE THREAD

**Issue by OnLiU211** [awslabs/aws-serverless-express#188]
```
const serverless = require('aws-serverless-express')
const express = require('express')
const app = express()
app.post('/some', async (request, response) => {
  response.json({ some: 'thing' })
})
const server = serverless.createServer(app)
exports.handler = /* this */ async /* this */ (event, context) => serverless.proxy(server, event, context)
```

I want to run exports.handler asynchronously, timeout each time with the following error.

```
ERROR: aws-serverless-express error
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:202:9)
    at getEventBody (/var/task/node_modules/aws-serverless-express/src/index.js:25:17)
    at mapApiGatewayEventToHttpRequest (/var/task/node_modules/aws-serverless-express/src/index.js:46:18)
    at forwardRequestToNodeServer (/var/task/node_modules/aws-serverless-express/src/index.js:135:28)
    at proxy (/var/task/node_modules/aws-serverless-express/src/index.js:202:7)
    at Server.startServer.on (/var/task/node_modules/aws-serverless-express/src/index.js:206:32)
    at emitNone (events.js:111:20)
    at Server.emit (events.js:208:7)
    at emitListeningNT (net.js:1394:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
```

I tried to figure out how to solve it, but I did not know it, so I made an issue.
Can I get help?

**Comment by OnLiU211** [comment]
Oh.
I have solved it.
https://github.com/awslabs/aws-serverless-express/issues/181
