### ISSUE TITLE
Getting error HPE_UNEXPECTED_CONTENT_LENGTH

### ISSUE THREAD

**Issue by watermelo** [awslabs/aws-serverless-express#243]
Hello，I found an error when using the aws-serverless-express，details as follow

```
at Socket.socketOnData (_http_client.js:408:20)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
at Socket.Readable.push (_stream_readable.js:208:10)
at Pipe.onread (net.js:607:20) bytesParsed: 536, code: 'HPE_UNEXPECTED_CONTENT_LENGTH' }
```

the response header as follow:
```
access-control-allow-headers →DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,api_key,Authorization
access-control-allow-methods →GET, POST, PUT, DELETE, OPTIONS
access-control-allow-origin →*
connection →keep-alive
content-type →application/json; charset=UTF-8
date →Tue, 16 Jul 2019 03:56:51 GMT
server →nginx/1.14.0 (Ubuntu)
total-count →60
transfer-encoding →chunked
```

So the chunked transfer encoding not supported by aws-serverless-express?

**Comment by brettstack** [comment]
That's right. This is because API Gateway doesn't support chunked transfer.

**Comment by watermelo** [comment]
thanks for the reply.
