### ISSUE TITLE
Cannot find module '@vendia/serverless-express/middleware'

### ISSUE THREAD

**Issue by ddbhagat** [awslabs/aws-serverless-express#367]
Hi 

I am trying to migrate from `aws-serverless-express` to `@vendia/serverless-express`. I could not see an option to use middleware from new package. 
So started using it like

```

const serverlessExpressMiddleware = require('@vendia/serverless-express/middleware');

app.use(awsServerlessExpressMiddleware.eventContext())

```
getting below error

```
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '@vendia/serverless-express/middleware'
Require stack:
- ${PROJECT_PATH}dist/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.@vendia/serverless-express/middleware (${PROJECT_PATH}dist/server.js:2495:18)
    at __webpack_require__ (${PROJECT_PATH}dist/server.js:3145:41)
    at eval (webpack-internal:///./src/Server.tsx:27:35)
    at Object../src/Server.tsx (${PROJECT_PATH}dist/server.js:20:1)
    at __webpack_require__ (${PROJECT_PATH}dist/server.js:3145:41)
    at ${PROJECT_PATH}dist/server.js:3296:18 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '${PROJECT_PATH}dist/server.js' ]

```

**Comment by brettstack** [comment]
Please see https://github.com/vendia/serverless-express/blob/mainline/UPGRADE.md. I'm considering adding support to make v4 as backwards-compatible as possible to make it easier to upgrade.

**Comment by brettstack** [comment]
v4.3.0 adds support for most of v3
