### ISSUE TITLE
Unable to determine event source based for running an async lambda function

### ISSUE THREAD

**Issue by vincevannoort-egalit** [awslabs/aws-serverless-express#401]
Dear Reader,

I have gotten the following error when trying to configure a function to run async, running it sync does work.

Any ideas why this is happening?

```
{
    "errorType": "Error",
    "errorMessage": "Unable to determine event source based on event.",
    "stack": [
        "Error: Unable to determine event source based on event.",
        "    at getEventSourceNameBasedOnEvent (/var/task/node_modules/@vendia/serverless-express/src/event-sources/utils.js:79:9)",
        "    at proxy (/var/task/node_modules/@vendia/serverless-express/src/configure.js:37:51)",
        "    at Runtime.handler (/var/task/node_modules/@vendia/serverless-express/src/configure.js:95:12)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
```

**Comment by brett-vendia** [comment]
As in you're doing an async invoke within your code? What does the event body look like?

**Comment by brettstack** [comment]
Do you have example code?

**Comment by aliamrani** [comment]
Hi Vince,

I just ran into the same issue and for our case, in which we invoke our Lambdas through API Gateway, enabling the "Use Lambda Proxy integration" option in the integration request of the method did the job for me.

Hope it helps.

**Comment by eHattori** [comment]
I have the same problem here, any else solution for this case?

**Comment by JeffML** [comment]
I tried the solution offered [here](https://github.com/vendia/serverless-express/issues/416) and it worked for me. Does not seem like the correct way to do it, though.
