### ISSUE TITLE
integration: lambda gives "Unable to determine event source based on event."

### ISSUE THREAD

**Issue by PeterTrotter** [awslabs/aws-serverless-express#416]
Hi all,

When deploying using `serverless` with `serverless-api-gateway-caching` like so:

```
functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
        integration: lambda
        caching:
          enabled: true
          cacheKeyParameters:
            - name: integration.request.header.bodyValue
              mappedFrom: method.request.body
```

The event is structured like this:

```
{
  body: {
    ...gql...
  },
  method: 'POST',
  principalId: '',
  stage: 'dev',
  cognitoPoolClaims: { sub: '' },
  enhancedAuthContext: {},
  headers: {
    Accept: '*/*',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-GB,en;q=0.5',
    'cache-control': 'no-cache',
    'CloudFront-Forwarded-Proto': 'https',
    'CloudFront-Is-Desktop-Viewer': 'true',
    'CloudFront-Is-Mobile-Viewer': 'false',
    'CloudFront-Is-SmartTV-Viewer': 'false',
    'CloudFront-Is-Tablet-Viewer': 'false',
    'CloudFront-Viewer-Country': 'GB',
    'content-type': 'application/json',
    dnt: '1',
    Host: '...host url...',
    origin: 'https://...origin url...',
    pragma: 'no-cache',
    Referer: 'https://...referrer url...',
    'sec-gpc': '1',
    'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0',
    Via: '2.0 xxxxxx.cloudfront.net (CloudFront)',
    'X-Amz-Cf-Id': 'xxxxxx',
    'X-Amzn-Trace-Id': 'Root=xxxxxx',
    'X-Forwarded-For': '...some ips...',
    'X-Forwarded-Port': '443',
    'X-Forwarded-Proto': 'https'
  },
  query: {},
  path: {},
  identity: {
    cognitoIdentityPoolId: '',
    accountId: '',
    cognitoIdentityId: '',
    caller: '',
    sourceIp: '...ip...',
    principalOrgId: '',
    accessKey: '',
    cognitoAuthenticationType: '',
    cognitoAuthenticationProvider: '',
    userArn: '',
    userAgent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0',
    user: ''
  },
  stageVariables: {},
  requestPath: '/graphql'
}
```

It seems you cannot enable `method.request.body` `cacheKeyParameters` without `integration: lambda` which seems to mess with the `event`.

Should this be an event type we are able to handle or am I missing a setting to turn it in to an event that can be handled?

**Comment by brettstack** [comment]
Looks like `event.requestContext` is missing from that https://github.com/vendia/serverless-express/blob/mainline/src/event-sources/utils.js#L75. If you remove `caching` does this work?  Is this an API Gateway V1 or V2 setup?

**Comment by PeterTrotter** [comment]
This is an API Gateway V2 setup.

I'm certain that the caching is a red herring here and the issue is the type integration.

Lambda vs Lambda Proxy

https://docs.aws.amazon.com/apigateway/latest/developerguide/getting-started-with-lambda-integration.html

As I understand it if you wish to allow caching for GraphQL (i.e. based on the request body) then you have to use Lambda integration instead of Lambda Proxy.

Switching to `integration: lambda-proxy` (obviously caching needs to remain disabled) works just fine.

Is the Lambda integration type beyond the scope of this project?

**Comment by PeterTrotter** [comment]
Sorry for wasting your time - looks like the correct way to use this for my setup (apollo-server) is to use GET requests for queries which bypasses the need to use the body as a cache key. Which means there is no need to change from Lambda Proxy to Lambda.

https://www.apollographql.com/docs/apollo-server/requests/

**Comment by dmattia** [comment]
This should be reopened. @PeterTrotter may have had luck using `integration: lambda-proxy`, but others do need to use `integration: lambda` and this issue persists

**Comment by brettstack** [comment]
Happy to leave this open and review any PRs adding non-proxy support.

**Comment by codyseibert** [comment]
We recently ran into this issue.  Make sure your api gateway integration request is setup with a template mapping to set the `requestContext`

**Comment by bumi** [comment]
https://github.com/vendia/serverless-express/issues/427#issuecomment-924580007

**Comment by gaestradaaedo** [comment]
I still cant get it going. I tried the following combinations using "@vendia/serverless-express" and "lambda-tester" with nodejs, express and internal routing for an AWS Serverless Lambda with API Gateway with SAM.

**app.js**
`
const express = require('express');
const cors = require('cors');
const compression = require('compression');

const app = new express();
app.use(express.json({ limit: '6mb', extended: true }));
app.use(express.urlencoded({ limit: '6mb', extended: true }));
app.use(cors());
app.use(compression());

// Testing endpoint
app.get('/', (req, res) => {
    res.send('Hello World');
});

//Must be included AWS SAM
module.exports = app;
`

**lamba.js**
`
 const serverlessExpress = require('@vendia/serverless-express');
 const app = require('./app');
 exports.handler = serverlessExpress({app});
`

**test-handler.js**
`
'use strict';
const myLambda = require('../../lambda');
const LambdaTester = require('lambda-tester');
const chai = require('chai');
const expect = chai.expect;

//First try
describe('Tests index', function () {
    it('verifies successful response', async function () {
        return await LambdaTester(myLambda.handler)
            .event()
            .expectResult((result) => {
                expect(result.message).to.be.equal("Hello World");
            });
    });
});

//Second try
describe('Tests index', function () {
    it('verifies successful response', function () {
        return LambdaTester(myLambda.handler)
            .event()
            .expectResult((result) => {
                expect(result.message).to.be.equal("hello world");
            });
    });
});

//Third try
describe('Tests index', function () {
    it('verifies successful response', function () {
       LambdaTester(myLambda.handler)
            .event()
            .expectResult((result) => {
                expect(result.message).to.be.equal("hello world");
            });
    });
});
`

And everytime i get the same error - **Error: Unable to determine event source based on event.**

Anyone knows what to do?

**Comment by electerious** [comment]
Getting the same error when using @vendia/serverless-express via apollo-server-lambda on Vercel.

```
[POST] /api
19:28:08:34
2022-01-09T18:28:10.719Z	2014d7ba-295d-4344-a94a-007608d4788b	ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"Unable to determine event source based on event.","stack":["Error: Unable to determine event source based on event.","    at getEventSourceNameBasedOnEvent (/var/task/node_modules/@vendia/serverless-express/src/event-sources/utils.js:88:9)","    at proxy (/var/task/node_modules/@vendia/serverless-express/src/configure.js:38:51)","    at handler (/var/task/node_modules/@vendia/serverless-express/src/configure.js:99:12)","    at Object.handler (/var/task/node_modules/apollo-server-lambda/dist/ApolloServer.js:51:27)"]}
```

**Comment by sebastien-abbal** [comment]
I had this problem with `serverless-plugin-warmup`, and i need to set my payload event like this:
```json
{
  "body": null,
  "httpMethod": "GET",
  "path": "/my-path",
  "requestContext": {}
}
```

--> Now, it's all working well :)

**Comment by alakdam07** [comment]
Can anyone please help me with my issue: https://stackoverflow.com/questions/71360059/apollo-server-lambda-unable-to-determine-event-source-based-on-event

**Comment by pbassut** [comment]
@sebastien-abbal Issue here was the same: missing a requestContext

**Comment by thadeu** [comment]
We had the same problem.

**Event:**

```yml
events:
  - http:
      path: /webhooks/logs/export
      method: POST
      async: true
```

**Problem**

```json
{
    "statusCode": 400,
    "headers": {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Credentials": true,
        "Date": "Wed, 29 Mar 2023 18:31:06 GMT"
    },
    "body": "{\"data\":null,\"errors\":[\"Unable to determine event source based on event.\"]}"
}
```

**Resolution**

```js
const handler = serverlessExpress({ app })

function overrideAsyncEventToExpress(event: any) {
  event.path = '/export'
  event.requestContext = { identity: event?.identity }
  event.httpMethod = event.method
  event.queryStringParameters = Object.assign(event.query, (event?.queryStringParameters || {}))
  event.pathParameters = { proxy: '' }
  event.isBase64Encoded = event?.isBase64Encoded || false
  event.body = typeof event.body != 'string' ? JSON.stringify(event.body) : event.body
  event.multiValueHeaders = event.headers

  return event
}

export async function main(
  event: APIGatewayEvent,
  context: Context,
): Promise<APIGatewayProxyResult> {
  logger.debug('Event', event)

  let eventPath = event?.requestPath || event?.resource || null

  try {
    if (eventPath === '/webhooks/logs/export') {
      overrideAsyncEventToExpress(event)
    } else if (eventPath === '/webhooks/logs') {
      event.path = '/'
    }

    return handler(event, context)
  } catch (error) {
    logger.error(error)

    const statusCode = error.statusCode || 400
    return Response.Fail({ statusCode, body: '', errors: [error?.message] })
  }
}
```

Basically we need to factory some methods to event object when received Async Event from `API Gateway`

```js
event.requestContext = { identity: event?.identity }
event.httpMethod = event.method
event.queryStringParameters = Object.assign(event.query, (event?.queryStringParameters || {}))
event.pathParameters = { proxy: '' }
event.isBase64Encoded = event?.isBase64Encoded || false
event.body = typeof event.body != 'string' ? JSON.stringify(event.body) : event.body
event.multiValueHeaders = event.headers
````

This is awful, because we need to manipulate event, so each change will be analyze because will could be a problem for us.

**Comment by 0xPT** [comment]
Not using this package due to ^ this

Why can't we add a default event type and then custom overrides?

**Comment by brettstack** [comment]
Hey @0xPT , does this help? https://github.com/CodeGenieApp/serverless-express?tab=readme-ov-file#eventsource

**Comment by 0xPT** [comment]
@brettstack unfortunately not, the documentation (and example) isn't clear enough, and this issue is pointing out the problem with having to redeclare every request/response properly.

My use case was Cognito triggers, and even trying to utilize the eventSource prop I 1) faced the error this issue brings up and 2) felt uncomfortable retyping the expected request/response object

**Comment by brettstack** [comment]
Which trigger specifically are you trying to use? I can add native support.

**Comment by CharlieGreenman** [comment]
Hey any update on this one? Still coming across this bug

**Comment by brettstack** [comment]
What trigger/event source are you using

**Comment by CharlieGreenman** [comment]
I am using aws lambda (proxy), with api gateway served over cloudfront. I just literally rolled back to aws-serverless-express (and can confirm site now works when rolled back) but would like to use a maintained library if possible. This is for an Angular x SSR deployment(using tech stack in article here: https://medium.com/razroo/how-to-deploy-angular-universal-using-aws-enterprise-grade-3637a5ebbc94).

@brettstack  If helpful I can pass along generic cloudformation code so can inspect what went into the deploy as well as the server.ts code?

**Comment by brettstack** [comment]
Just pasting the `server.ts` should be enough, but have you first followed the upgrade doc if you're going from 3 to 4? https://github.com/CodeGenieApp/serverless-express/blob/mainline/UPGRADE.md

**Comment by CharlieGreenman** [comment]
I followed the migration based on docs to the best of my ability. `server.ts` gist can be seen here: https://gist.github.com/CharlieGreenman/4f3e5aa032e7a3aef3f7837a816b2b90

**Comment by brettstack** [comment]
Try this for some additional debugging:

```
// NOTE: if you call that outside of your handler you'll get a performance boost.
const serverlessExpressInstance = serverlessExpress({
  app: server,
  binaryMimeTypes,
  log: {
    debug: (...props) => console.debug(...props),
    error: (...props) => console.error(...props)
  }
});

export const lambda_handler = (event: APIGatewayEvent, context: Context): Promise<APIGatewayProxyResult> => {
  // const { event, context } = getCurrentInvoke()
  console.log(`Event: ${JSON.stringify(event)}`);
  console.log(`Context: ${JSON.stringify(context)}`);
  if(context) {
    context.callbackWaitsForEmptyEventLoop = false;
  }
  // NOTE: it's also recommended not to try/catch here as serverless-express handles this for you and returns a 500 to APIGW; your Lambda function will technically succeed, so you'll want to monitor APIGW for 500 rather than Lambda errors
  return serverlessExpressInstance(event, context)
};
```

Could you post the event and context you're getting?

**Comment by aaronatbissell** [comment]
I've been following this thread pretty closely as we have been seeing similar problems. 

It turns out our problem was that our `Content-Type` header was upper-case (should be `content-type`). There are some packages down the line that make some decisions based on the `content-type` header and they assume all header names will be lower-case. 

Maybe an enhancement request for this library - if we are trying to make the `req` object look like a Node.js HTTP request object, then it should probably include the logic to lower-case all the HTTP headers. Even though we are satisfying the shape of an HTTP object, we aren't satisfying the behavior.

https://nodejs.org/api/http.html#messageheaders

**Comment by Ascend84** [comment]
I'm getting the same error with a different setup:

- API Gateway with a proxy path (e.g. /api/orders/{proxy+})
- Not using SAM, but want to deploy later through CDK

with the following server.ts:
```
import serverlessExpress from "@codegenie/serverless-express";
import {router} from "./appRouter";
import express from "express";

const app = express();

app.use("/", router);

export const lambdaHandler = serverlessExpress({ app });
```

So calling the Lambda function from the API Gateway results in the "Unable to determine event source based on event." error.

**Comment by AbulSyed** [comment]
Encounter same error when migrating `apollo-server-lambda` from v2 to v3, resolved by adding `requestContext` to payload.
