### ISSUE TITLE
"Runtime.ImportModuleError: Error: Cannot find module 'lambda'" in production

### ISSUE THREAD

**Issue by LeeviKopakkala** [awslabs/aws-serverless-express#473]
Using the https://github.com/vendia/serverless-express/tree/mainline/examples/basic-starter-api-gateway-v2-typescript as a base. 

Running the project locally works perfectly. No errors and sending requests works correctly.

After configuring and deploying the function with `yarn deploy`, Stack and Lambda function are up and visible in AWS Console and the deployment is successful.

The issue comes after trying out the API endpoint.
Tried investigating the issue and there seems to be a similar issue with older version of serverless-express but couldn't find any that would apply to the latest one.

Sending a request returns `Internal Server Error`with Stack trace of:

```
2021-10-11T12:30:09.701+03:00

Copy
2021-10-11T09:30:09.700Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'lambda'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'lambda'",
        "Require stack:",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1072:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)",
        "    at Module.load (internal/modules/cjs/loader.js:937:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:778:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

Have ran `yarn upgrade --latest`

Package.json:

```
"name": "api-gateway",
  "version": "1.0.0",
  "description": "ApiGateway",
  "main": "./lambda.js",
  "config": {
    "s3BucketName": "",
    "region": "",
    "cloudFormationStackName": "",
    "functionName": ""
  },
  "scripts": {
    "watch": "nodemon ./src/app.local.ts",
    "test": "jest",
    "cdk": "cdk",
    "lint": "eslint .",
    "setup": "yarn install && (cross-var aws s3api get-bucket-location --bucket $npm_package_config_s3BucketName --region $npm_package_config_region || yarn create-bucket) && yarn package-deploy",
    "create-bucket": "cross-var aws s3 mb s3://$npm_package_config_s3BucketName --region $npm_package_config_region",
    "package-deploy": "yarn build && yarn package && yarn deploy",
    "build": "tsc",
    "package": "cross-var aws cloudformation package --template ./sam-template.yaml --s3-bucket $npm_package_config_s3BucketName --output-template sam-template.packaged.yaml --region $npm_package_config_region",
    "deploy": "cross-var aws cloudformation deploy --template-file sam-template.packaged.yaml --stack-name $npm_package_config_cloudFormationStackName --capabilities CAPABILITY_IAM --region $npm_package_config_region --parameter-overrides DomainName=$npm_package_config_domain"
  },
  "devDependencies": {
    "@aws-cdk/core": "^1.123.0",
    "@types/compression": "^1.7.2",
    "@types/cors": "^2.8.12",
    "@types/express": "^4.17.13",
    "@types/jsonwebtoken": "^8.5.5",
    "aws-lambda": "^1.0.6",
    "copy-webpack-plugin": "^9.0.1",
    "cross-var": "^1.1.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "nodemon": "^2.0.12",
    "source-map-support": "^0.5.19",
    "ts-node": "^10.2.1",
    "tslint": "^6.1.3",
    "typescript": "^4.4.3",
    "webpack": "^5.21.2",
    "webpack-cli": "^4.5.0"
  },
  "dependencies": {
    "@aws-cdk/aws-ec2": "^1.123.0",
    "@aws-cdk/aws-lambda-nodejs": "^1.123.0",
    "@aws-cdk/aws-ssm": "^1.123.0",
    "@k-foss/ts-esnode": "^2.0.2",
    "@vendia/serverless-express": "^4.3.0",
    "aws-cdk": "^1.123.0",
    "axios": "^0.22.0",
    "body-parser": "^1.17.1",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "dotenv": "^10.0.0",
    "ejs": "^3.1.6",
    "express": "^4.17.1",
    "fp-ts": "^2.10.5",
    "io-ts": "^2.2.16",
    "io-ts-types": "^0.5.16",
    "jsonwebtoken": "^8.5.1",
    "jwks-rsa": "^2.0.3"
  },
```

**Comment by LeeviKopakkala** [comment]
Issue was fixed by changing:

```
      CodeUri: ./dist
      PackageType: Zip
      Runtime: nodejs14.x
      Handler: lambda.handler
```

To:

```
      CodeUri: .
      PackageType: Zip
      Runtime: nodejs14.x
      Handler: dist/lambda.handler
      ```
