### ISSUE TITLE
The header content contains invalid characters

### ISSUE THREAD

**Issue by mihaerzen** [awslabs/aws-serverless-express#60]
When running local test with the following `api-gateway-event.json`:

```json
{
  "httpMethod": "GET",
  "//body": "{\"name\": \"Jake\"}",
  "path": "/users",
  "resource": "/{proxy+}",
  "queryStringParameters": {
    "foo": "💩"
  },
  "pathParameters": {},
  "headers": {},
  "requestContext": {}
}
```

the following error occurs:

```
TypeError: The header content contains invalid characters
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:358:11)
    at new ClientRequest (_http_client.js:86:14)
    at Object.exports.request (http.js:31:10)
    at forwardRequestToNodeServer (/Users/johnDoe/Developer/github.com/aws-serverless-express/example/node_modules/aws-serverless-express/index.js:115:22)
    at Server.startServer.on.error (/Users/johnDoe/Developer/github.com/aws-serverless-express/example/node_modules/aws-serverless-express/index.js:165:21)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1285:10)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Any idea how to avoid this? Basically anyone adding weird character (emoji) to a query parameter can now crash the app.

**Comment by mihaerzen** [comment]
Forgot to mention this obviously happens in lambda as well.

**Comment by kahouieong** [comment]
Since NodeJS 5.6 changed that HTTP header parsing now aligns more closely with the HTTP spec including restricting the acceptable characters, you can catch the error and return an error back.

**Comment by brettstack** [comment]
Coming from here https://github.com/awslabs/aws-serverless-express/blob/master/index.js#L29 - encoding the event from api gateway into headers so they can be accessed in Express

**Comment by brettstack** [comment]
Will release today

**Comment by brettstack** [comment]
Released. Please update to version 3.0.0
