### ISSUE TITLE
npm setup issues

### ISSUE THREAD

**Issue by waltermvp** [awslabs/aws-serverless-express#84]
Having issues running `npm run setup `, i followed the setup instructions and have the follwing aws version installed `aws --version
aws-cli/1.11.16 Python/2.7.10 Darwin/16.6.0 botocore/1.4.73`
That said fairly new to node + serverless (im coming from iOS), so apologies if im missing something obvious, but any help would be greatly appreciated. 

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/Users/waltermvp/.nvm/versions/node/v8.1.2/bin/node',
1 verbose cli   '/Users/waltermvp/.nvm/versions/node/v8.1.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'setup' ]
2 info using npm@5.0.3
3 info using node@v8.1.2
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle aws-serverless-express-example@2.1.1~presetup: aws-serverless-express-example@2.1.1
6 silly lifecycle aws-serverless-express-example@2.1.1~presetup: no script for presetup, continuing
7 info lifecycle aws-serverless-express-example@2.1.1~setup: aws-serverless-express-example@2.1.1
8 verbose lifecycle aws-serverless-express-example@2.1.1~setup: unsafe-perm in lifecycle true
9 verbose lifecycle aws-serverless-express-example@2.1.1~setup: PATH: /Users/waltermvp/.nvm/versions/node/v8.1.2/lib/node_modules/npm/bin/node-gyp-bin:/Users/waltermvp/Development/Open Source/aws-serverless-express/example/node_modules/.bin:/Users/waltermvp/.nvm/versions/node/v8.1.2/bin:/Users/waltermvp/.rvm/gems/ruby-2.3.3/bin:/Users/waltermvp/.rvm/gems/ruby-2.3.3@global/bin:/Users/waltermvp/.rvm/rubies/ruby-2.3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/waltermvp/.rvm/bin:/usr/local/git/bin:/usr/local/bin
10 verbose lifecycle aws-serverless-express-example@2.1.1~setup: CWD: /Users/waltermvp/Development/Open Source/aws-serverless-express/example
11 silly lifecycle aws-serverless-express-example@2.1.1~setup: Args: [ '-c',
11 silly lifecycle   'npm install && (aws s3api get-bucket-location --bucket $npm_package_config_s3BucketName --region $npm_package_config_region || npm run create-bucket) && npm run package-deploy' ]
12 silly lifecycle aws-serverless-express-example@2.1.1~setup: Returned: code: 2  signal: null
13 info lifecycle aws-serverless-express-example@2.1.1~setup: Failed to exec setup script
14 verbose stack Error: aws-serverless-express-example@2.1.1 setup: `npm install && (aws s3api get-bucket-location --bucket $npm_package_config_s3BucketName --region $npm_package_config_region || npm run create-bucket) && npm run package-deploy`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/Users/waltermvp/.nvm/versions/node/v8.1.2/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/waltermvp/.nvm/versions/node/v8.1.2/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid aws-serverless-express-example@2.1.1
16 verbose cwd /Users/waltermvp/Development/Open Source/aws-serverless-express/example
17 verbose Darwin 16.6.0
18 verbose argv "/Users/waltermvp/.nvm/versions/node/v8.1.2/bin/node" "/Users/waltermvp/.nvm/versions/node/v8.1.2/bin/npm" "run" "setup"
19 verbose node v8.1.2
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 2
23 error aws-serverless-express-example@2.1.1 setup: `npm install && (aws s3api get-bucket-location --bucket $npm_package_config_s3BucketName --region $npm_package_config_region || npm run create-bucket) && npm run package-deploy`
23 error Exit status 2
24 error Failed at the aws-serverless-express-example@2.1.1 setup script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 2, true ]

```

**Comment by brettstack** [comment]
Can you try updating the AWS CLI? My version is 1.11.82 and I'm not sure which version the package+deploy commands were added.

**Comment by waltermvp** [comment]
This is the output using `waltermvp@Walters-iMac:~/Development/Open Source/aws-serverless-express/example (master)$ aws --version
0.2.5`

```bash

waltermvp@Walters-iMac:~/Development/Open Source/aws-serverless-express/example (master)$ npm run setup

> aws-serverless-express-example@2.1.1 setup /Users/waltermvp/Development/Open Source/aws-serverless-express/example
> npm install && (aws s3api get-bucket-location --bucket $npm_package_config_s3BucketName --region $npm_package_config_region || npm run create-bucket) && npm run package-deploy

npm WARN aws-serverless-express-example@2.1.1 No repository field.

up to date in 1.485s
usage: aws [-h] [-v] {as,ec2,elb} ...
aws: error: invalid choice: 's3api' (choose from 'as', 'ec2', 'elb')

> aws-serverless-express-example@2.1.1 create-bucket /Users/waltermvp/Development/Open Source/aws-serverless-express/example
> aws s3 mb s3://$npm_package_config_s3BucketName --region $npm_package_config_region

usage: aws [-h] [-v] {as,ec2,elb} ...
aws: error: invalid choice: 's3' (choose from 'as', 'ec2', 'elb')
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! aws-serverless-express-example@2.1.1 create-bucket: `aws s3 mb s3://$npm_package_config_s3BucketName --region $npm_package_config_region`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the aws-serverless-express-example@2.1.1 create-bucket script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/waltermvp/.npm/_logs/2017-06-19T22_54_29_703Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! aws-serverless-express-example@2.1.1 setup: `npm install && (aws s3api get-bucket-location --bucket $npm_package_config_s3BucketName --region $npm_package_config_region || npm run create-bucket) && npm run package-deploy`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the aws-serverless-express-example@2.1.1 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/waltermvp/.npm/_logs/2017-06-19T22_54_29_775Z-debug.log

```

Thanks for you help :)

**Comment by waltermvp** [comment]
@brettstack

**Comment by brettstack** [comment]
Wow, I am not sure how you get version `0.2.5`. In your first post you have version `1.11.16`. If you can upgrade to latest AWS CLI it should work.

Also, it looks like you're using Node.js 8. I recommend using the same version as the Lambda function 6.10.

**Comment by waltermvp** [comment]
@brettstack  i think i was confused bewtween `aws` && `awscli` are they two different entities?

**Comment by waltermvp** [comment]
looks like they are not, Appears i need to figure out my aws issues first. Closing for now, thanks!

**Comment by waltermvp** [comment]
@brettstack it worked with `waltermvp@Walters-iMac:~$ aws --version
aws-cli/1.11.107 Python/2.7.10 Darwin/16.6.0 botocore/1.5.70` thanks !!
