### ISSUE TITLE
Getting error HPE_UNEXPECTED_CONTENT_LENGTH 

### ISSUE THREAD

**Issue by roshancsc** [awslabs/aws-serverless-express#89]
Hi all,
I am using this package and I am getting error  as aws-serverless-express connection error with below details. 

Error: Parse Error
at Error (native)
at Socket.socketOnData (_http_client.js:362:20)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
at Socket.Readable.push (_stream_readable.js:134:10)
at Pipe.onread (net.js:547:20) bytesParsed: 943, code: 'HPE_UNEXPECTED_CONTENT_LENGTH' }

Can anyone suggest why I am getting this error.

**Comment by brettstack** [comment]
Based on this https://github.com/request/request/issues/2091 you get this error when both `Content-Length` and `Transfer-Encoding=chunked` are in response headers. This library strips out `transfer-encoding` headers, so it must be throwing this error higher up the stack (i.e. in your app). Try inspecting the headers and remove one of those headers if they both exist.

**Comment by roshancsc** [comment]
Thanks implementing @brettstack suggestion fix this issue
